BRIGHT_TURQUOISE = "#1DDCFB"
WILD_STRAWBERRY = "#FF2B83"
BLACK_PEARL = "#071437"

PRIMARY_COLOR = BRIGHT_TURQUOISE
SECONDARY_COLOR = WILD_STRAWBERRY
BACKGROUND_COLOR = BLACK_PEARL

PRIMARY_FONT="Oxanium"
