BRIGHT_TURQUOISE = "#1DDCFB"
WILD_STRAWBERRY = "#FF2B83"
BLACK_PEARL = "#071437"

BRIGHT_GREEN="#22D860"
DEEP_BLUE="#0032E1"

PRIMARY_COLOR = BRIGHT_TURQUOISE
SECONDARY_COLOR = WILD_STRAWBERRY
HIGHLIGHT_COLOR = BRIGHT_GREEN
HIGHLIGHT2_COLOR = DEEP_BLUE
BACKGROUND_COLOR = BLACK_PEARL

PRIMARY_FONT="Oxanium"
