#!/bin/sh
osascript -e 'quit app "QuickTime Player"' || echo "QuickTime Player not running"

if [ "$1" == "" ]; then
    quality_arg="-ql"
else
    quality_arg=$1
fi

echo python3 -m manim -p $quality_arg zkmarek/video/main.py
python3 -m manim -p $quality_arg zkmarek/video/main.py

