#!/bin/sh
rm -fr elliptic_curves EllipticCurves
manim --save_sections elliptic/main.py
manim_editor --quick_present_export media/videos/main/1080p60/sections/EllipticCurves.json
python3 -m http.server 8000 --directory EllipticCurves
