#!/bin/sh

rm -fr elliptic_curves Episode7
if [ "$1" = "-qk" ]; then
    res="2160p60"
elif [ "$1" = "-ql" ]; then
    res="480p15"
else
    res="1080p60"
fi

python -m manim --save_sections zkmarek/video/main.py $1
manim_editor --quick_present_export media/videos/main/$res/sections/Episode7.json &&
python -m http.server 8000 --directory Episode7
